# Generated by Django 3.2.3 on 2021-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='휴대폰 번호')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='계정 이름')),
                ('fullname', models.CharField(max_length=30, verbose_name='사용자 이름')),
                ('is_active', models.BooleanField(default=False, verbose_name='계정활성')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
